springdoc:
  api-docs:
    enabled: true
    path: /api/v1/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui

logging:
  level:
    com.annepolis.lexiconmeum: DEBUG
    com.annepolis.lexiconmeum.ingest.wiktionary.WiktionaryLexicalDataParser: DEBUG
app:
  load:
    data-file: file:/opt/lexiconmeum/data/lexicalData.jsonl
    parse-mode: LENIENT