logging:
  level:
    com.annepolis.lexiconmeum: DEBUG
    com.annepolis.lexiconmeum.shared.data.load.WiktionaryLexicalDataParser: DEBUG
app:
  load:
    data-file: ${APP_DATA_FILE:file:/opt/lexiconmeum/data/lexicalData.jsonl}
    parse-mode: LENIENT