logging:
  level:
    com.annepolis.lexiconmeum: DEBUG
    com.annepolis.lexiconmeum.ingest.wiktionary.WiktionaryLexicalDataParser: DEBUG
app:
  load:
    data-file: file:/opt/lexiconmeum/data/lexicalData.jsonl
    parse-mode: LENIENT