logging:
  level:
    com.annepolis.lexiconmeum: DEBUG
    com.annepolis.lexiconmeum.ingest.wiktionary.WiktionaryLexicalDataParser: TRACE
app:
  load:
    data-file: ${APP_DATA_FILE:file:/opt/lexiconmeum/data/lexicalData.jsonl}
    parse-mode: LENIENT